### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by cuileri** [dicg2020/dicg2020.github.io#2]
Are we fine with the current list of topics? @llegard, what could you add from your field?

- Distributed algorithms
- Trust and reputation systems
- Fault-tolerance
- Gossip-based learning and behavioral models
- Self-sovereign identity
- Peer-to-peer networks
- Game-theoretic approaches to tragedy of commons
- Markets, mechanism design, and incentives
- Computational social choice

**Comment by llegard** [comment]
I do not think that Middleware will accept any papers on ethics of technology. I do have some suggestions though:

- incentives for participants 
- fairness in market systems
- decnentralized governance

**Comment by synctext** [comment]
Website looks really good. We need to beg for content asap ...
